export class td_outward_payment {
  public ardb_cd:string;
  public brn_cd: string;
  public trans_dt: Date;
  public trans_cd: number;
  public payment_type: string;
  public bene_name: string;
  public bene_code: string;
  public amount: number;
  public charge_ded: number;
  public date_of_payment: Date;
  public bene_acc_no: string;
  public bene_ifsc_code: string;
  public dr_acc_no: number;
  public bene_email_id: string;
  public bene_mobile_no: number;
  public bank_dr_acc_type: number;
  public bank_dr_acc_no: string;
  public bank_dr_acc_name: string;
  public credit_narration: string;
  public payment_ref_no: string;
  public status: string;
  public rejection_reason: string;
  public processing_remarks: string;
  public cust_ref_no: string;
  public value_date: Date;
  public created_by: string;
  public created_dt: Date;
  public modified_by: string;
  public modified_dt: Date;
  public approved_by: string;
  public approved_dt: Date;
  public approval_status: string;
}
